### ISSUE TITLE
Fix installation from GitHub

### ISSUE THREAD

**Issue by lucasczz** [online-ml/river-torch#19]
Currently, trying to install the package from GitHub with `pip install https://github.com/online-ml/river-torch --upgrade` leads to the following error:

> ERROR: Cannot unpack file /tmp/pip-unpack-8zu6salu/river-torch (downloaded from /tmp/pip-req-build-mlo_scrb, content-type: text/html; charset=utf-8); cannot detect archive format
> ERROR: Cannot determine archive format of /tmp/pip-req-build-mlo_scrb

**Comment by ercangunbilek** [comment]
Up

**Comment by kulbachcedric** [comment]
Hi, 
for the moment, you can try to install it with `pip install https://github.com/online-ml/river-torch/archive/refs/heads/master.zip`.

Best 
Cedric

**Comment by ercangunbilek** [comment]
> 

This also gives an error.

**Comment by lucasczz** [comment]
Installation from GitHub should now work as intended. (Tested on Google Colab with Python 3.7 and locally with Python 3.10)
