### ISSUE TITLE
PyPI install errors

### ISSUE THREAD

**Issue by ercangunbilek** [online-ml/river-torch#21]
<img width="1480" alt="Ekran Resmi 2022-07-17 10 52 30" src="https://user-images.githubusercontent.com/33091962/179389227-e39473e5-0ae1-4570-9f7b-8ced7e222384.png">

**Comment by kulbachcedric** [comment]
Hi @ercangunbilek,

thanks for the report! 
Do you have the OS and the Python Version you are using? 

Best
Cedric

**Comment by ercangunbilek** [comment]
```
!pip uninstall torch
!pip install torch==1.12.0
```

**Comment by kulbachcedric** [comment]
Hi @ercangunbilek, 

this issue is solved within v0.0.14.

Best
Cedric
