### ISSUE TITLE
Can you use ProbabilityWeightedAutoencoder with some parameters ?

### ISSUE THREAD

**Issue by ercangunbilek** [online-ml/river-torch#22]
I want to use  ProbabilityWeightedAutoencoder with 2 encoder network layer + latent dim + 2 decoder network layer ? But when adding parameter to the get_fc_encoder i am taking error.

**If I do not specify n_features, I am taking error which is"n_features is not entered".**

<img width="1187" alt="Ekran Resmi 2022-07-19 22 35 27" src="https://user-images.githubusercontent.com/33091962/179833987-8425169d-a7f6-4f6c-928c-75c1c90d46ad.png">

**If I enter n_features then I am taking error which is "unexpected keyword argument n_features".**

<img width="1326" alt="Ekran Resmi 2022-07-19 22 35 59" src="https://user-images.githubusercontent.com/33091962/179834008-f61eeb7b-2524-41df-94ee-9dfa3f75a1f4.png">

**Comment by lucasczz** [comment]
Since the model expects functions for `encoder_fn` and `decoder_fn`, you have to define it as 
`ProbabilityWeightedAutoencoder(encoder_fn=get_fc_encoder, decoder_fn=get_fc_decoder, n_layers=2, lr=0.01`).
