### ISSUE TITLE
ProbabilityWeightedAutoencoder has no attribute to_init

### ISSUE THREAD

**Issue by ercangunbilek** [online-ml/river-torch#26]
<img width="1101" alt="Ekran Resmi 2022-07-20 18 36 26" src="https://user-images.githubusercontent.com/33091962/180024105-26eb8ef6-bac8-43e0-b9de-f02d5fdf79ea.png">

**Comment by kulbachcedric** [comment]
@ercangunbilek we just fixed this issue ☺️

Best Cedric
