### ISSUE TITLE
Is there a way to load weights?

### ISSUE THREAD

**Issue by albertobotana** [online-ml/river-torch#27]
Is there any way to load weights to a wrapped classifier from PyTorch? Our team is currently working with a pre-trained model with fine-tuned weights, so having a way to load them would be crucial. We have tried loading the weights as part of the `build_fn` function, but it doesn't seem to work, as the model performance indicates no improvement whether we load the weights this way or not. I have looked everywhere on this repo but couldn't find anything useful.

If there's no way to do that right now, are there any future plans to implement such feature?

**Comment by kulbachcedric** [comment]
Hi @albertobotana,
for now, there is no function that allows loading a pretrained model into a classifier, as it takes a `build_fn`. The reason for that parameter is to automatically indicate the number of input features while initializing the architecture with the first instance of the data stream. A dirty fix would be to change the `.net` parameter of the classifier class with the pretrained architecture. 

We are at the beginning of the framework and one enhancement is definitely to allow loading pretrained models. I'll add it to the issue board. 

Best
Cedric
