### ISSUE TITLE
Can you add a new examples for anomaly detection ?

### ISSUE THREAD

**Issue by ercangunbilek** [online-ml/river-torch#31]
Codes are constantly changing. I can't catch the change. Code that works one day doesn't work the next. Many modules have been modified. Please update and increase samples for abnormal status detection

**Comment by ercangunbilek** [comment]
Up

**Comment by ercangunbilek** [comment]
When will you publish new documentation for anomaly ?

**Comment by kulbachcedric** [comment]
Hi @ercangunbilek,
a new Version of the documentation is now online.
However, it is a lot of work to build a comprehensive documentation...

We'll add new examples in the upcoming two weeks! 

Best
Cedric
