### ISSUE TITLE
The anomaly detection example on the home page does not work. 

### ISSUE THREAD

**Issue by ercangunbilek** [online-ml/river-torch#6]
The Autoencoder anomaly detection example on the home page does not work. Can you please update? I tried many methods but couldn't get it to work.

**Comment by kulbachcedric** [comment]
Hi @ercangunbilek,
I just released a new version, where some errors are fixed.
Could you please try to reinstall (still) DeepRiver? 

If it is still not working, please upload the error.

**Comment by ercangunbilek** [comment]
Hi @kulbachcedric ,
I think you should update document. Here's how I solved the problem for my own app.
1) People should install via " pip install river-torch " don't " pip install DeepRiver ".
2) You should update the example of anomaly detection via Autoencoder that on the home page of repository. Because, in there , write "build_fn=get_fully_conected_autoencoder" but you have been changed build_fn via "encoder_fn" and "decoder_fn" . Please update and stay up-to-date .
By the way , you are doing great things.
Congratulations.

**Comment by MaxHalford** [comment]
> You should update the example of anomaly detection via Autoencoder that on the home page of repository. Because, in there , write "build_fn=get_fully_conected_autoencoder" but you have been changed build_fn via "encoder_fn" and "decoder_fn" . Please update and stay up-to-date .

@kulbachcedric I encourage you to write doctests to prevent these kind of issues. It kills two birds with one stone by documenting as well as testing your code. Tell me if you would like some help to set this up :)

**Comment by kulbachcedric** [comment]
> > You should update the example of anomaly detection via Autoencoder that on the home page of repository. Because, in there , write "build_fn=get_fully_conected_autoencoder" but you have been changed build_fn via "encoder_fn" and "decoder_fn" . Please update and stay up-to-date .
> 
> @kulbachcedric I encourage you to write doctests to prevent these kind of issues. It kills two birds with one stone by documenting as well as testing your code. Tell me if you would like some help to set this up :)

 @MaxHalford  It would be great if you have a minimal example of how I can implement it!
