### ISSUE TITLE
Add LSTM Autoencoder

### ISSUE THREAD

**Issue by ercangunbilek** [online-ml/river-torch#7]
Hi @kulbachcedric ,
Can you add LSTM Autoencoder module. For anomaly detection ?

**Comment by kulbachcedric** [comment]
Hi @ercangunbilek,
we have implemented the `RollingWindowAutoencoder` in `river_test.anomaly` with the right encoder and decoder build function it should do the job ☺️.

**Comment by lucasczz** [comment]
Example implementations for LSTM Autoencoders can be found in https://online-ml.github.io/river-torch/examples/anomaly/example_lstm_autoencoder/ .
