### ISSUE TITLE
Autoencoder want to n_features at the parameter ?

### ISSUE THREAD

**Issue by ercangunbilek** [online-ml/river-torch#9]
Autoencoder want to n_features at the parameter. But I am adding n_features at the parameter and then program shows error message.

**Comment by MaxHalford** [comment]
@ercangunbilek, even though Cedric might be able to debug your problem, I would highly recommend that in the future you take the time to share a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). It helps software maintainers tremendously.

**Comment by ercangunbilek** [comment]
The error in the document is the same as mine. "river_torch.anomaly.nn_builder.get_fc_encoder() got multiple values for keyword argument n_features"

```
from river import feature_extraction as fx
from river import compose, stats,anomaly,preprocessing
import numbers
import DeepRiver
import math
from river import datasets, metrics
from river_torch.anomaly.nn_builder import get_fc_encoder
from river_torch.anomaly.nn_builder import get_fc_decoder
from river_torch.anomaly import ProbabilityWeightedAutoencoder
from river_torch.utils import get_activation_fn
from torch import manual_seed, nn


def build_autoencoder_model():

    numerical_features = compose.Pipeline(
            compose.SelectType(float),
            preprocessing.StandardScaler())
    
    preModel = numerical_features
    
    model = compose.Pipeline(
        preModel,
        ProbabilityWeightedAutoencoder(encoder_fn=get_fc_encoder,decoder_fn=get_fc_decoder, lr=0.01, n_features=5))
    return model
```
```

import math

from river import datasets, metrics
from river_torch.anomaly.nn_builder import get_fc_encoder
from river_torch.anomaly.nn_builder import get_fc_decoder
from river_torch.utils import get_activation_fn
from torch import manual_seed, nn
from river import stream

_ = manual_seed(0)


if __name__ == '__main__':

  metric = metrics.ROCAUC()
  dataframe['target'] = dataframe['target'].astype(bool)
  data = dataframe.iloc[:,:-1]
  target = dataframe.iloc[:,-1]

  model = build_autoencoder_model()

  for x, y in stream.iter_pandas(data, target):
          score = model.score_one(x)
          metric.update(y_true=y, y_pred=score)
          model.learn_one(x=x)
  print(f'ROCAUC: {metric.get()}')
```
The error is **TypeError: get_fc_encoder() got multiple values for keyword argument 'n_features'**

**Comment by kulbachcedric** [comment]
@ercangunbilek try to reinstall it with ´pip install river-torch. I just saw that the release 0.0.12 was already uploaded to river-torch. 
Sorry, my bad

**Comment by ercangunbilek** [comment]
Problem not solved.

> The problem is, if I don't give any parameters at first, the code works. However, when I enter n_layer as a parameter later, it tells me to enter n_features as a parameter. When I enter it as well, I get the error "forward() got an unexpected keyword argument n_features".

**Comment by kulbachcedric** [comment]
@ercangunbilek Could you provide me with the model you're trying to use?

**Comment by lucasczz** [comment]
@ercangunbilek I think that the issue might be that the way in which the Autoencoder base-class (and most other estimators for that matter) is implemented at the moment, you are not supposed to explicitly pass `n_features` as a parameter, since the number of features is inferred from the model input the first time `score_one` or `learn_one` is called.

**Comment by ercangunbilek** [comment]
> @ercangunbilek Could you provide me with the model you're trying to use?


If you share google account, then I can share with you.
> @ercangunbilek Could you provide me with the model you're trying to use?

**Comment by ercangunbilek** [comment]
> > @ercangunbilek I think that the issue might be that the way in which the Autoencoder base-class (and most other estimators for that matter) is implemented at the moment, you are not supposed to explicitly pass `n_features` as a parameter, since the number of features is inferred from the model input the first time `score_one` or `learn_one` is called.
> 
> @ercangunbilek Try `ProbabilityWeightedAutoencoder(encoder_fn=get_fc_encoder,decoder_fn=get_fc_decoder, lr=0.01)` without the n_features argument.

Yes, it works but I want to change some changes in parameter. If I changes , I will face to face some errors.

**Comment by ercangunbilek** [comment]
Is it different from the classical model, where we first train the network with normal data and then detect anomalies with a reconstruction error? Shouldn't we first give clean data here? Do we need to give mixed (Abnormal and normal)?

**Comment by lucasczz** [comment]
1. Yes, the model detects anomalies based on their reconstruction error. 
2. No you don't necessarily have to train on clean data first. At the moment, all models follow the same principle as river in that no pre-training is performed before stream evaluation, although you could simply call `learn_one` on each sample of a clean dataset if you wanted to pre-train anyways.

**Comment by ercangunbilek** [comment]
> * Yes, the model detects anomalies based on their reconstruction error.
> * No you don't necessarily have to train on clean data first. At the moment, all models follow the same principle as most river models in that no pre-training is performed before stream evaluation, although you could simply call `learn_one` on each sample of a clean dataset if you wanted to pre-train anyways.



> * Yes, the model detects anomalies based on their reconstruction error.
> * No you don't necessarily have to train on clean data first. At the moment, all models follow the same principle as most river models in that no pre-training is performed before stream evaluation, although you could simply call `learn_one` on each sample of a clean dataset if you wanted to pre-train anyways.

Thank you @lucasczz .
